name: Azure Function Deploy With CICD.
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
jobs: 
  deploy-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: x64

      - name: Install required python modules
        run: |
            cd ./AzureStorageQueueTriggerFunction
            python -m pip install --upgrade pip
            pip install --target="./.python_packages/lib/site-packages" -r requirements.txt 

      - name: Zip the Azure Function Deploy folder
        run: |
          cd AzureStorageQueueTriggerFunction
          zip -r ../AzureStorageQueueTriggerFunction.zip ./*

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          app-name: 'TestAPIMDA'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
