name: Conditional Terraform with Follow-up

on:
  workflow_dispatch:
    inputs:
      environment_group:
        description: 'Select Environment Group'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - SIT
          - UAT
          - UAT1
          - PROD

      configuration:
        description: 'Select Configuration'
        required: true
        default: 'snow'
        type: choice
        options:
          - snow
          - cds
          - dms
          - abc

jobs:
  sit_apply:
    name: Terraform Apply for SIT
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.environment_group == 'SIT' &&
      github.event.inputs.configuration == 'snow'
    steps:
      - name: Terraform Apply (SIT)
        run: |
          echo "✅ Applying SIT Terraform (snow)"
          #terraform init
          #terraform apply -auto-approve

  uat_apply:
    name: Terraform Apply for UAT
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.environment_group == 'UAT' &&
      github.event.inputs.configuration == 'snow'
    steps:
      - name: Terraform Apply (UAT)
        run: |
          echo "✅ Applying UAT Terraform (snow)"
          #terraform init
          #terraform apply -auto-approve

  follow_up:
    name: Follow-up Job After SIT or UAT
    runs-on: ubuntu-latest
    needs: [sit_apply, uat_apply]
    if: |
      (needs.sit_apply.result == 'success' || needs.uat_apply.result == 'success') &&
      (github.event.inputs.environment_group == 'SIT' || github.event.inputs.environment_group == 'UAT') &&
      github.event.inputs.configuration == 'snow'
    steps:
      - name: Post-deployment Task
        run: |
          echo "🎉 Follow-up triggered for ${{ github.event.inputs.environment_group }} with configuration ${{ github.event.inputs.configuration }}"
