name: Trigger Pipeline on Push and Assign Config

on:
  push:
    paths:
      - 'AzureStorageQueueTriggerFunction/**'
      - 'functionapp/**'

jobs:
  assign-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Assign Config for AzureStorageQueueTriggerFunction
        if: ${{ contains(github.event.paths, 'AzureStorageQueueTriggerFunction/') }}
        run: |
          echo "Changes detected in AzureStorageQueueTriggerFunction folder"
          config="AzureStorageQueueTriggerFunction_Config"
          echo "Config is set to: $config"

      - name: Assign Config for functionapp
        if: ${{ contains(github.event.paths, 'functionapp/') }}
        run: |
          echo "Changes detected in functionapp folder"
          config="functionapp_Config"
          echo "Config is set to: $config"
