name: Identify Changes by Path

on:
  push:
    paths:
      - 'AzureStorageQueueTriggerFunction/**'
      - 'functionapp/**'

jobs:
  detect-path:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Identify Changed Path
        run: |
          if git diff --name-only $GITHUB_SHA^ $GITHUB_SHA | grep -q '^AzureStorageQueueTriggerFunction/'; then
            echo "Detected changes in AzureStorageQueueTriggerFunction"
            echo "config=AzureStorageQueueTriggerFunction" >> $GITHUB_ENV
          elif git diff --name-only $GITHUB_SHA^ $GITHUB_SHA | grep -q '^functionapp/'; then
            echo "Detected changes in functionapp"
            echo "config=functionapp_Config" >> $GITHUB_ENV
          else
            echo "No matching folder changes detected "
