name: PR to Main Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'AzureStorageQueueTriggerFunction/**'  # Trigger if there are changes in folder1
      - 'functionapp/**'  # Trigger if there are changes in folder2

jobs:
  set-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine changes and set config value
        id: set_config
        run: |
          # Initialize config variable
          CONFIG="default"

          # Check if changes are made to folder1
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^functionapp/"; then
            CONFIG="functionapp"
          fi

          # Check if changes are made to folder2
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^AzureStorageQueueTriggerFunction/"; then
            CONFIG="AzureStorageQueueTriggerFunction"
          fi

          # Export the config value as an environment variable
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      - name: Print the config value
        run: |
          echo "The assigned config value is: ${{ env.CONFIG }}, ${{ github.event.before }} ${{ github.sha }} "

