name: Override ENV Variable Example

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    env:
      MY_VARIABLE: 'initial_value'  # Set initial value
    steps:
      - name: Print initial value
        run: echo "Initial value: $MY_VARIABLE"

      - name: Override env variable for subsequent steps
        run: |
          echo "MY_VARIABLE=overridden_value" >> $GITHUB_ENV

      - name: Print overridden value
        run: echo "Overridden value: $MY_VARIABLE"
